### ISSUE TITLE
Sorting news not working by 'calendarize'

### ISSUE THREAD

**Issue by p380** [lochmueller/calendarize_news#14]
Sorting by event 'start_date' does not work in the news module.

**Comment by lochmueller** [comment]
Hey @p380 
this issue is very old. Sorry... I did'nt check this in the past. The calendarize plugin is "always" sorted by start_date. i think you talked about the news plugin, right? The news plugin itself is not part of this extension. Please check EXT:news resources to solve this problem. I will close the issue. If I am wrong, feel free to reopen the issue and send us more information.
Regards,
Tim
